web:
  build: .
  dockerfile: Dockerfile.node
  ports:
    - "8080:8080"
  environment:
    NODE_ENV: production
  links:
    - "db"
db:
  build: .
  dockerfile: Dockerfile.cassandra
  ports:
    - "9042:9042"
    - "9160:9160"
